name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Configure conan
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: conan install --build=missing .-s build_type=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: conan build . -s build_type= ${{env.BUILD_TYPE}}

